version: '3.9'
services:
  neo4j: 
    image: marcellodesales/neo4j-with-cypher-seed:latest
    environment:
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=test
    ports: 
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j-runtime/data:/data
      - ./neo4j-runtime/logs:/logs
      - ./neo4j-runtime/import:/var/lib/neo4j/import
      - ./neo4j-runtime/plugins:/plugins
      - ./init_user.cql:/cyphers/init_user.cql
