name: Build Hexhive Docs
on:
  push:
    branches:
      - staging

jobs:
  build_docs:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: lerna bootstrap --scope=@hexhive/docs --include-dependencies

      - run: lerna run build --scope @hexhive/docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./packages/core-apps/hexhive-docs/build # The folder the action should deploy.
