name: Build Hexhive Apps (Flow + Command)
on:
  push:
    branches:
      - staging

jobs:
  build_command:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: lerna bootstrap --scope=@hexhive-apps/command --include-dependencies

      - name: Build web
        run: NODE_ENV=production CI=false REACT_APP_API=https://api.hexhive.io/command npm run build-app:command

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Upload new web-build
        run: |
          aws s3 sync packages/apps/hive-command/build/ s3://${{ secrets.S3_STAGING_COMMAND_BUCKET }} --delete
  build_flow:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: lerna bootstrap --scope=@hexhive-apps/flow --include-dependencies

      - name: Build web
        run: NODE_ENV=production CI=false REACT_APP_API=https://api.hexhive.io/flow npm run build-app:flow

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Upload new web-build
        run: |
          aws s3 sync packages/apps/hive-flow/build/ s3://${{ secrets.S3_STAGING_FLOW_BUCKET }} --delete
      
  build_flow_backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: ls

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push 
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./HiveFlow.Dockerfile
          push: true
          tags: thetechcompany/hive-flow:latest-next
          build-args: |
            BUILD_ENV=github
  
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
  build_command_backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: ls

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push 
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./HiveCommand.Dockerfile
          push: true
          tags: thetechcompany/hive-command:latest-next
          build-args: |
            BUILD_ENV=github
  
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      