name: Build Dashboard

on:
  push: 
    branches:
      - signage

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build and push 
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./HiveSignage.Dockerfile
          push: true
          tags: thetechcompany/hive-signage:latest
          build-args: |
            BUILD_ENV=github

  
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
