name: Build Hexhive Apps (Flow + Command)
on:
  push:
    branches:
      - staging

jobs:
  build_web:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        apps: [DASHBOARD, FLOW, COMMAND]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: npm i

      - run: lerna bootstrap

      - name: Build web
        run: NODE_ENV=production CI=false REACT_APP_API=https://api.hexhive.io npm run build:${{ matrix.apps }}
      
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Upload new web-build
        run: |
          aws s3 sync packages/apps/hive-command/build/ s3://${{ secrets['S3_STAGING_' + matrix.apps + '_BUCKET']}} --delete

