name: Build Hexhive Apps (Flow + Command)
on:
  push:
    branches:
      - master

jobs:
  build_command:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: lerna bootstrap --scope=@hexhive-apps/command --include-dependencies

      - name: Build web
        run: NODE_ENV=production CI=false REACT_APP_API=https://api.hexhive.io/command npm run build-app:command

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Upload new web-build
        run: |
          aws s3 sync packages/apps/hive-command/build/ s3://${{ secrets.S3_COMMAND_BUCKET }} --delete
  build_flow:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: lerna bootstrap --scope=@hexhive-apps/flow --include-dependencies

      - name: Build web
        run: NODE_ENV=production CI=false REACT_APP_API=https://api.hexhive.io/flow npm run build-app:flow

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Upload new web-build
        run: |
          aws s3 sync packages/apps/hive-flow/build/ s3://${{ secrets.S3_FLOW_BUCKET }} --delete
      