name: Build Core-Apps Staging

on:
  push:
    branches:
      - staging
    paths: ["packages/core-apps/**"]

jobs:
  build_coreapps:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        apps: [dashboard, header, settings]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn

      - run: lerna bootstrap --scope @hexhive-core/${{ matrix.apps }} --include-dependencies

      - run: export REACT_APP_API="https://staging-api.hexhive.io"
      - run: export REACT_APP_URL="https://next.hexhive.io"
      - run: export PUBLIC_PATH="https://staging-apps.hexhive.io/${{matrix.apps}}/"
      
      - name: Build web
        run: (export REACT_APP_URL="https://next.hexhive.io" PUBLIC_PATH="https://staging-apps.hexhive.io/${{matrix.apps}}/" REACT_APP_API="https://staging-api.hexhive.io" NODE_ENV=production CI=false; lerna run build --scope @hexhive-core/${{ matrix.apps }} --include-dependencies)
      
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: Make Bucket URL
        run: echo "BUCKET_URL=S3_STAGING_${{matrix.apps}}_BUCKET" | tr a-z A-Z >> $GITHUB_ENV

      - name: Upload new web-build
        run: |
          aws s3 sync packages/core-apps/hive-${{ matrix.apps }}/dist/ s3://${{ secrets.STAGING_APP_BUCKET }}/${{matrix.apps}} --delete
