name: DB Infrastructure

on:
  push:
    branches:
      - staging
      - master
    paths: ["packages/infrastructure/db/**"]

concurrency: db-infra-${{ github.ref }}


jobs:
  push_db_infra:
    name: Update DB Infra
    runs-on: ubuntu-latest
    env: 
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ap-southeast-2
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: yarn
        working-directory: ./packages/infrastructure/db

      - name: Setup stack
        run: |
          echo "STACK_NAME=ultraviolet/db-staging" >> $GITHUB_ENV
        if: ${{ GITHUB_REF#refs/heads/ == staging }}

      - name: Setup stack
        run: |
          echo "STACK_NAME=ultraviolet/db-prod" >> $GITHUB_ENV
        if: ${{ GITHUB_REF#refs/heads/ == master }}
        
      - name: Update infrastructure
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ env.STACK_NAME }}
          work-dir: ./packages/infrastructure/db
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

