name: PR Validator (Staging)
on:
  pull_request:
    branches:
      - staging
jobs:
  preview-infra:
    name: Preview Infra changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ap-southeast-2
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - run: npm i
        working-directory: ./packages/infrastructure/apps

      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: ultraviolet/staging
          work-dir: ./packages/infrastructure/apps
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  
  preview-db:
    name: Preview DB Migration
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - run: pulumi stack select ultraviolet/staging
        working-directory: ./packages/infrastructure/apps

      - run: echo "::set-output name=kubeconfig::$(pulumi stack output kubeconfig)" 
        working-directory: ./packages/infrastructure/apps
        id: kube_config

      - run: echo "::set-output name=postgres::$(pulumi stack output postgres_name )" 
        working-directory: ./packages/infrastructure/apps
        id: postgres_url
      
      - run: echo "::set-output name=pass::$(pulumi stack output postgres_pass )" 
        working-directory: ./packages/infrastructure/apps
        id: postgres_pass
        
      - uses: actions-hub/kubectl@master
        env: 
          KUBE_CONFIG: ${{ steps.kube_config.outputs.kubeconfig }}
        with:
          args: port-forward ${{ steps.postgres_url.outputs.postgres }} 5432:5432

      - run: npx prisma migrate status
        env:
          DATABASE_URL: postgresql://postgres:${{ steps.postgres_pass.outputs.pass }}@localhost:5432/postgres
        working-directory: ./packages/core/hexhive-data/