name: Publish

on:
  push:
    branches:
      - staging
    paths: [".github/workflows/publish-modules.yml", "packages/clients/**", "packages/core/**", "packages/shared/**", "packages/workers/**"]


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Use NodeJS 16"
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: |
        yarn install --immutable --immutable-cache

    - name: Build # Build all packages
      run: npx lerna exec npm run build

    - name: Setup NPM Token
      run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

    - name: "Version and publish" # Interesting step
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"

        if [ ${{ github.ref_name }} = staging ]; then
          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        else
          npx lerna version --conventional-commits --conventional-graduate --yes
        fi

        npx lerna publish from-git --yes --no-verify-access
